import 'dart:async';
import 'dart:math' as math;
import 'package:flutter/material.dart';
import 'package:geolocator/geolocator.dart';
import 'package:flutter_tts/flutter_tts.dart';
import 'package:maplibre_gl/mapbox_gl.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:convert';
import 'package:http/http.dart' as http;

class PlaceResult{final String name;final double lat,lon;PlaceResult(this.name,this.lat,this.lon);}
class RouteResult{final List<LatLng> points;final double km,minutes;RouteResult(this.points,this.km,this.minutes);}

Future<List<PlaceResult>> searchPlaces(String query) async {
  final uri=Uri.https('nominatim.openstreetmap.org','/search',{'q':query,'format':'jsonv2','limit':'5','addressdetails':'1'});
  final r=await http.get(uri,headers:{'User-Agent':'TerekDrive/2.4 (+TerekDrive navigation app)'});
  if(r.statusCode!=200)throw Exception('Поиск: HTTP ${r.statusCode}');
  final data=jsonDecode(r.body) as List;
  return data.map((e)=>PlaceResult(e['display_name'] as String,double.parse(e['lat'] as String),double.parse(e['lon'] as String))).toList();
}
Future<RouteResult> buildRoute(Position from,PlaceResult to) async {
  final uri=Uri.parse('https://router.project-osrm.org/route/v1/driving/${from.longitude},${from.latitude};${to.lon},${to.lat}?overview=full&geometries=geojson&steps=true');
  final r=await http.get(uri,headers:{'User-Agent':'TerekDrive/2.4'});
  if(r.statusCode!=200)throw Exception('Маршрут: HTTP ${r.statusCode}');
  final data=jsonDecode(r.body) as Map<String,dynamic>;
  if(data['code']!='Ok')throw Exception('Маршрут не найден');
  final route=(data['routes'] as List).first as Map<String,dynamic>;
  final coords=((route['geometry'] as Map)['coordinates'] as List).map((p)=>LatLng((p[1] as num).toDouble(),(p[0] as num).toDouble())).toList();
  return RouteResult(coords,(route['distance'] as num).toDouble()/1000,(route['duration'] as num).toDouble()/60);
}


const bg=Color(0xFF07090C),panel=Color(0xFF10151B),red=Color(0xFFFF3B30),cyan=Color(0xFF00D9FF),green=Color(0xFF00E5A0);
void main()=>runApp(const TerekDriveApp());
class TerekDriveApp extends StatelessWidget{const TerekDriveApp({super.key});Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Терек Драйв',theme:ThemeData.dark(useMaterial3:true).copyWith(scaffoldBackgroundColor:bg,colorScheme:const ColorScheme.dark(primary:red,secondary:cyan)),home:const DriveShell());}
class DriveShell extends StatefulWidget{const DriveShell({super.key});State<DriveShell> createState()=>_DriveShellState();}
class _DriveShellState extends State<DriveShell>{int tab=0;Position? pos;StreamSubscription<Position>? gps;bool sound=true,tracking=false;final tts=FlutterTts();void initState(){super.initState();_load();}Future<void>_load()async{final p=await SharedPreferences.getInstance();if(mounted)setState(()=>sound=p.getBool('sound')??true);}Future<void>_gps()async{if(!await Geolocator.isLocationServiceEnabled())return;var q=await Geolocator.checkPermission();if(q==LocationPermission.denied)q=await Geolocator.requestPermission();if(q==LocationPermission.denied||q==LocationPermission.deniedForever)return;await gps?.cancel();gps=Geolocator.getPositionStream(locationSettings:const LocationSettings(accuracy:LocationAccuracy.best,distanceFilter:2)).listen((p){if(mounted)setState(()=>pos=p);});if(mounted)setState(()=>tracking=true);}Future<void>_sound()async{final p=await SharedPreferences.getInstance();final n=!sound;await p.setBool('sound',n);if(mounted)setState(()=>sound=n);}void dispose(){gps?.cancel();tts.stop();super.dispose();}Widget build(BuildContext c){final pages=[MapPage(position:pos,onLocate:_gps),NavigationPage(position:pos,tts:tts,sound:sound),SpeedPage(position:pos,tracking:tracking,onStart:_gps),SettingsPage(sound:sound,onSound:_sound)];return Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.map_outlined),selectedIcon:Icon(Icons.map),label:'Карта'),NavigationDestination(icon:Icon(Icons.navigation_outlined),selectedIcon:Icon(Icons.navigation),label:'Навигация'),NavigationDestination(icon:Icon(Icons.speed_outlined),selectedIcon:Icon(Icons.speed),label:'Скорость'),NavigationDestination(icon:Icon(Icons.settings_outlined),selectedIcon:Icon(Icons.settings),label:'Настройки')]));}}
class MapPage extends StatefulWidget{final Position?position;final VoidCallback onLocate;const MapPage({super.key,this.position,required this.onLocate});State<MapPage>createState()=>_MapPageState();}
class _MapPageState extends State<MapPage>{MapLibreMapController?map;static const home=LatLng(43.3178,45.6985);Widget build(BuildContext c)=>Stack(children:[MapLibreMap(styleString:'https://tiles.openfreemap.org/styles/liberty',initialCameraPosition:const CameraPosition(target:home,zoom:10),myLocationEnabled:true,onMapCreated:(x)=>map=x),Positioned(top:12,left:12,right:12,child:const Header('ТЕРЕК ДРАЙВ','MAP / FLUTTER ENGINE')),Positioned(bottom:18,right:16,child:FloatingActionButton(backgroundColor:red,onPressed:(){widget.onLocate();final p=widget.position;if(p!=null)map?.animateCamera(CameraUpdate.newLatLngZoom(LatLng(p.latitude,p.longitude),14));},child:const Icon(Icons.my_location)))]);}
class NavigationPage extends StatefulWidget{final Position?position;final FlutterTts tts;final bool sound;const NavigationPage({super.key,this.position,required this.tts,required this.sound});State<NavigationPage>createState()=>_NavigationPageState();}
class _NavigationPageState extends State<NavigationPage>{final q=TextEditingController();MapLibreMapController?map;List<PlaceResult>results=[];PlaceResult?selected;RouteResult?route;bool busy=false;String?error;
Future<void>say(String s)async{if(!widget.sound)return;await widget.tts.setLanguage('ru-RU');await widget.tts.setSpeechRate(.48);await widget.tts.speak(s);}
Future<void>search()async{final text=q.text.trim();if(text.isEmpty)return;setState((){busy=true;error=null;results=[];});try{final r=await searchPlaces(text);if(!mounted)return;setState(()=>results=r);if(r.isNotEmpty){setState(()=>selected=r.first);await showRoute(r.first);}}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
Future<void>showRoute(PlaceResult place)async{final p=widget.position;if(p==null){setState(()=>error='Сначала включи GPS');return;}setState((){busy=true;error=null;selected=place;});try{final rr=await buildRoute(p,place);if(map!=null&&rr.points.length>1){await map!.clearLines();await map!.addLine(LineOptions(geometry:rr.points,lineColor:'#00D9FF',lineWidth:6,lineOpacity:.9));await map!.animateCamera(CameraUpdate.newLatLngBounds(_bounds(rr.points),left:40,right:40,top:160,bottom:260));}if(mounted){setState(()=>route=rr);await say('Маршрут построен. ${rr.km.toStringAsFixed(1)} километра. Время ${rr.minutes.round()} минут.');}}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}
LatLngBounds _bounds(List<LatLng> p){var minLat=p.first.latitude,maxLat=p.first.latitude,minLon=p.first.longitude,maxLon=p.first.longitude;for(final x in p){minLat=math.min(minLat,x.latitude);maxLat=math.max(maxLat,x.latitude);minLon=math.min(minLon,x.longitude);maxLon=math.max(maxLon,x.longitude);}return LatLngBounds(southwest:LatLng(minLat,minLon),northeast:LatLng(maxLat,maxLon));}
void dispose(){q.dispose();super.dispose();}
Widget build(BuildContext c)=>Column(children:[const Padding(padding:EdgeInsets.fromLTRB(16,16,16,8),child:Header('НАВИГАЦИЯ','NOMINATIM / OSRM / ГЕНА')),Expanded(child:Stack(children:[MapLibreMap(styleString:'https://tiles.openfreemap.org/styles/liberty',initialCameraPosition:const CameraPosition(target:LatLng(43.3178,45.6985),zoom:10),myLocationEnabled:true,onMapCreated:(x)=>map=x),Positioned(top:10,left:12,right:12,child:Card(color:panel,child:Padding(padding:const EdgeInsets.all(8),child:Row(children:[Expanded(child:TextField(controller:q,onSubmitted:(_)=>search(),decoration:const InputDecoration(hintText:'Куда едем?',border:InputBorder.none))),IconButton(onPressed:busy?null:search,icon:busy?const SizedBox(width:20,height:20,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.search,color:cyan))])))),Positioned(bottom:10,left:12,right:12,child:Column(children:[if(results.isNotEmpty&&!busy)Card(color:panel,child:ConstrainedBox(constraints:const BoxConstraints(maxHeight:130),child:ListView(shrinkWrap:true,children:results.map((x)=>ListTile(dense:true,title:Text(x.name,maxLines:2,overflow:TextOverflow.ellipsis),onTap:()=>showRoute(x))).toList()))),if(route!=null)Card(color:panel,child:ListTile(leading:const Icon(Icons.navigation,color:cyan),title:Text('${route!.km.toStringAsFixed(1)} км • ${route!.minutes.round()} мин'),subtitle:Text(selected?.name??'Маршрут'),trailing:IconButton(onPressed:()=>say('Маршрут сохранён'),icon:const Icon(Icons.bookmark_border))))]))])),if(error!=null)Padding(padding:const EdgeInsets.all(6),child:Text(error!,style:const TextStyle(color:red))),Padding(padding:const EdgeInsets.fromLTRB(16,4,16,8),child:Row(children:[Expanded(child:Text(widget.position==null?'GPS не подключён':'GPS подключён',style:const TextStyle(color:cyan))),const Text('© OpenStreetMap contributors',style:TextStyle(fontSize:10,color:Colors.white54))]))]);}
class SpeedPage extends StatelessWidget{final Position?position;final bool tracking;final VoidCallback onStart;const SpeedPage({super.key,this.position,required this.tracking,required this.onStart});Widget build(BuildContext c){final v=position==null?0.0:math.max(0,position!.speed*3.6);return Column(children:[const SizedBox(height:18),const Header('SPEED','GPS LIVE / 300 KM/H'),Expanded(child:Center(child:CustomPaint(size:const Size(330,330),painter:GaugePainter(v.clamp(0,300))))),Text(v.round().toString(),style:const TextStyle(fontSize:64,fontWeight:FontWeight.w900)),const Text('KM/H • GPS LIVE',style:TextStyle(color:cyan,letterSpacing:2)),const SizedBox(height:16),FilledButton.icon(onPressed:onStart,icon:const Icon(Icons.gps_fixed),label:Text(tracking?'GPS АКТИВЕН':'ВКЛЮЧИТЬ GPS')),const SizedBox(height:20)]);}}
class SettingsPage extends StatelessWidget{final bool sound;final VoidCallback onSound;const SettingsPage({super.key,required this.sound,required this.onSound});Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(16),children:[const Header('НАСТРОЙКИ','TEREK DRIVE 2.4 / FLUTTER'),const SizedBox(height:20),Card(color:panel,child:SwitchListTile(title:const Text('Звук и Гена'),subtitle:const Text('Голосовые подсказки'),value:sound,onChanged:(_)=>onSound())),const Card(color:panel,child:ListTile(leading:Icon(Icons.cloud_download,color:cyan),title:Text('Офлайн-карты'),subtitle:Text('Выбор города и загрузка региона'))),const Card(color:panel,child:ListTile(leading:Icon(Icons.palette,color:red),title:Text('Сезонные темы'),subtitle:Text('Весна • Лето • Осень • Зима'))),const Card(color:panel,child:ListTile(leading:Icon(Icons.language,color:green),title:Text('Язык'),subtitle:Text('Русский • English • Deutsch • Français • Español')))]);}
class Header extends StatelessWidget{final String a,b;const Header(this.a,this.b,{super.key});Widget build(BuildContext c)=>Row(children:[Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900,letterSpacing:1.5)),Text(b,style:const TextStyle(color:cyan,fontSize:11,letterSpacing:1.2))])),const Icon(Icons.bolt,color:red)]);}
class ActionCard extends StatelessWidget{final String icon,title;final VoidCallback onTap;const ActionCard(this.icon,this.title,this.onTap,{super.key});Widget build(BuildContext c)=>Card(color:panel,child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(14),child:Padding(padding:const EdgeInsets.all(14),child:Column(children:[Text(icon,style:const TextStyle(fontSize:25)),const SizedBox(height:5),Text(title)]))));}
class GaugePainter extends CustomPainter{final double speed;GaugePainter(this.speed);void paint(Canvas c,Size s){final o=s.center,r=s.width*.42;c.drawCircle(o,r,Paint()..style=PaintingStyle.stroke..strokeWidth=13..color=red);final p=Paint()..color=Colors.white70..strokeWidth=2;for(int i=0;i<=30;i++){final a=-math.pi*.75+math.pi*1.5*i/30;c.drawLine(o+Offset(math.cos(a),math.sin(a))*r*.83,o+Offset(math.cos(a),math.sin(a))*r*.94,p);}final a=-math.pi*.75+math.pi*1.5*(speed/300);c.drawLine(o,o+Offset(math.cos(a),math.sin(a))*r*.78,Paint()..color=red..strokeWidth=6..strokeCap=StrokeCap.round);c.drawCircle(o,9,Paint()..color=Colors.white);}bool shouldRepaint(covariant GaugePainter old)=>old.speed!=speed;}
